Repository apify/apify-sdk-python, pull requests merged in 2023-05, with the labels that each got.

#90 feat: use test user token from organisation secrets
  .github/workflows/integration_tests.yaml
Labels: t-platform

#91 Save local key-value store records with the correct extension
  CHANGELOG.md
  src/apify/_memory_storage/file_storage_utils.py
  src/apify/_memory_storage/resource_clients/key_value_store.py
  tests/unit/memory_storage/resource_clients/test_key_value_store.py
Labels: bug, t-platform

#93 Invalidate cloudfront after deploying docs
  .github/workflows/docs.yaml
Labels: t-platform, adhoc
