Repository apify/apify-sdk-python, pull requests merged in 2023-12, with the labels that each got.

#145 docs: scrapy-migrator mention
  docs/02-guides/05-scrapy.mdx
Labels: documentation, t-tooling

#154 Add comment why not to use `~=` clause in deps definition
  pyproject.toml
Labels: adhoc, t-tooling

#155 Fix type hint problems for resource clients
  CHANGELOG.md
  src/apify/_memory_storage/resource_clients/base_resource_client.py
  src/apify/_memory_storage/resource_clients/dataset.py
  src/apify/_memory_storage/resource_clients/key_value_store.py
  src/apify/_memory_storage/resource_clients/request_queue.py
Labels: t-tooling

#157 Fix Scrapy Apify retry middleware
  CHANGELOG.md
  src/apify/scrapy/middlewares.py
Labels: t-tooling

#159 Add `pytest-cov` for unit-test coverage
  .gitignore
  CONTRIBUTING.md
  Makefile
  pyproject.toml
Labels: adhoc, t-tooling
