Repository apify/apify-sdk-python, pull requests merged in 2023-10, with the labels that each got.

#116 Update Apify log formatter to contain logger name
  CHANGELOG.md
  src/apify/event_manager.py
  src/apify/log.py
Labels: enhancement, adhoc, t-tooling

#120 Add release checklists
  CONTRIBUTING.md
Labels: t-tooling

#121 Add support for Python 3.12
  CHANGELOG.md
  pyproject.toml
  tests/unit/test_event_manager.py
Labels: t-tooling, tested

#124 Add Python 3.12 to CI
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/unit_tests.yaml
  CHANGELOG.md
  pyproject.toml
Labels: t-tooling

#127 chore: Check whether version in PR is already released
  .github/workflows/check_version_availability.yaml
  .github/workflows/run_checks.yaml
  Makefile
  scripts/check_version_availability.py
  scripts/update_version_for_prerelease.py
  scripts/utils.py
Labels: t-platform, adhoc

#129 Add checklist for upgrading Python version
  CONTRIBUTING.md
Labels: t-tooling
