Repository apify/apify-sdk-python, pull requests merged in 2023-08, with the labels that each got.

#102 Bump version to 1.1.2
  .flake8
  .isort.cfg
  CHANGELOG.md
  pyproject.toml
  src/apify/consts.py
  tests/integration/test_actor_api_helpers.py
Labels: t-tooling, tested

#103 chore: Code quality improvements
  pyproject.toml
  src/apify/_memory_storage/memory_storage_client.py
  src/apify/_memory_storage/resource_clients/base_resource_client.py
  src/apify/_memory_storage/resource_clients/key_value_store.py
  src/apify/_utils.py
  src/apify/actor.py
  src/apify/event_manager.py
  src/apify/storages/base_storage.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/actor/test_actor_log.py
  tests/unit/memory_storage/resource_clients/test_dataset.py
  tests/unit/memory_storage/resource_clients/test_request_queue.py
  tests/unit/test_utils.py
Labels: t-platform, adhoc, debt, tested

#105 feat: Use Actor env vars
  pyproject.toml
  src/apify/_utils.py
  src/apify/actor.py
  src/apify/config.py
  tests/integration/README.md
  tests/integration/test_actor_api_helpers.py
  tests/integration/test_fixtures.py
  tests/unit/actor/test_actor_dataset.py
  tests/unit/actor/test_actor_env_helpers.py
  tests/unit/test_config.py
  tests/unit/test_event_manager.py
  tests/unit/test_utils.py
Labels: t-platform, tested

#106 chore: Pin apify deps versions
  pyproject.toml
Labels: bug, t-platform, adhoc, high priority

#111 Update log integration tests after logging change on platform
  CHANGELOG.md
  pyproject.toml
  tests/integration/test_actor_log.py
Labels: t-platform, adhoc, tested

#112 Stop using `pytest-randomly` in tests
  CHANGELOG.md
  pyproject.toml
Labels: t-platform, adhoc
