Repository apify/apify-sdk-python, pull requests merged in 2023-02, with the labels that each got.

#59 Add more logging to flaky request queue integration test
  tests/integration/actor_source_base/src/__main__.py
  tests/integration/test_request_queue.py
Labels: t-platform, adhoc

#60 Fixed parsing messages from the platform events websocket when they have no event data
  CHANGELOG.md
  src/apify/event_manager.py
Labels: t-platform, adhoc

#58 Run unit tests on Windows as well
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/release.yml
  .github/workflows/run_checks.yaml
  .github/workflows/unit_tests.yaml
  CHANGELOG.md
  tests/unit/memory_storage/resource_clients/test_dataset.py
  tests/unit/memory_storage/resource_clients/test_key_value_store.py
  tests/unit/memory_storage/resource_clients/test_request_queue.py
Labels: t-platform, adhoc

#61 Unify GitHub workflow naming
  .github/workflows/pr_toolkit.yaml
  .github/workflows/release.yaml
Labels: t-platform, adhoc

#68 Adjust docs publishing workflow
  .github/workflows/docs.yml
  .gitignore
  Makefile
  setup.py
  website/pydoc-markdown.yml
  website/static/.nojekyll
Labels: t-platform, adhoc

#69 Add logger
  setup.py
  src/apify/_utils.py
  src/apify/actor.py
  src/apify/event_manager.py
  src/apify/log.py
  src/apify/proxy_configuration.py
  src/apify/storages/request_queue.py
  tests/integration/actor_source_base/src/__main__.py
  tests/integration/test_actor_log.py
  tests/unit/actor/test_actor_helpers.py
  tests/unit/actor/test_actor_log.py
  tests/unit/test_proxy_configuration.py
Labels: t-platform, adhoc

#67 feat: Add chunking mechanism to push_data, cleanup TODOs
  setup.py
  src/apify/actor.py
  src/apify/consts.py
  src/apify/memory_storage/memory_storage.py
  src/apify/memory_storage/resource_clients/request_queue.py
  src/apify/storages/dataset.py
  src/apify/storages/key_value_store.py
  src/apify/storages/request_queue.py
  tests/integration/test_actor_dataset.py
  tests/unit/memory_storage/resource_clients/test_request_queue.py
  tests/unit/storages/test_dataset.py
Labels: t-platform, adhoc, debt, high priority

#70 Fix handling the `MIGRATING` actor event
  src/apify/actor.py
  src/apify/event_manager.py
  tests/unit/actor/test_actor_lifecycle.py
Labels: t-platform, adhoc

#71 Added unit tests for `Configuration` and env vars handling
  CHANGELOG.md
  tests/unit/test_config.py
  tests/unit/test_consts.py
Labels: t-platform, adhoc

#72 `EventManager` improvements and unit tests
  CHANGELOG.md
  docs/docs.md
  src/apify/actor.py
  src/apify/event_manager.py
  tests/unit/actor/test_actor_env_helpers.py
  tests/unit/test_event_manager.py
Labels: t-platform, adhoc

#73 Add more Flake8 plugins, fix issues they reported
  .flake8
  CHANGELOG.md
  setup.py
  src/apify/_utils.py
  src/apify/memory_storage/resource_clients/dataset.py
  src/apify/memory_storage/resource_clients/key_value_store.py
  src/apify/memory_storage/resource_clients/request_queue.py
  src/apify/proxy_configuration.py
  tests/integration/conftest.py
  tests/integration/test_actor_log.py
  tests/unit/actor/test_actor_env_helpers.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/conftest.py
  tests/unit/memory_storage/resource_clients/test_dataset.py
  tests/unit/memory_storage/resource_clients/test_dataset_collection.py
  tests/unit/memory_storage/resource_clients/test_key_value_store.py
  tests/unit/memory_storage/resource_clients/test_key_value_store_collection.py
  tests/unit/memory_storage/resource_clients/test_request_queue.py
  tests/unit/memory_storage/resource_clients/test_request_queue_collection.py
  tests/unit/memory_storage/test_memory_storage.py
  tests/unit/storages/test_dataset.py
  tests/unit/storages/test_key_value_store.py
  tests/unit/storages/test_request_queue.py
  tests/unit/test_crypto.py
  tests/unit/test_event_manager.py
  tests/unit/test_lru_cache.py
  tests/unit/test_utils.py
Labels: t-platform, adhoc

#74 Remove `pydantic`
  docs/docs.md
  mypy.ini
  setup.py
  src/apify/actor.py
  src/apify/proxy_configuration.py
  tests/unit/test_proxy_configuration.py
Labels: t-platform, adhoc, debt

#75 Parse datetimes in actor events
  src/apify/_utils.py
  src/apify/actor.py
  src/apify/event_manager.py
  tests/integration/test_actor_events.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/test_utils.py
Labels: t-platform, adhoc

#76 Make sure local `RequestQueueClient` respects `forefront`
  CHANGELOG.md
  setup.py
  src/apify/memory_storage/resource_clients/request_queue.py
  tests/unit/memory_storage/resource_clients/test_request_queue.py
Labels: t-platform, adhoc

#77 Count `handledRequestCount` properly
  CHANGELOG.md
  src/apify/memory_storage/resource_clients/request_queue.py
  tests/unit/memory_storage/resource_clients/test_request_queue.py
Labels: t-platform, adhoc
