Repository apify/apify-sdk-python, pull requests merged in 2024-03, with the labels that each got.

#188 docs: clarify release instructions in CONTRIBUTING
  CONTRIBUTING.md
Labels: t-platform, adhoc

#191 Improve error handling for `to_apify_request` serialization failures
  CHANGELOG.md
  src/apify/scrapy/requests.py
  src/apify/scrapy/scheduler.py
  tests/unit/scrapy/requests/test_to_apify_request.py
Labels: adhoc, debt, t-tooling, tested

#192 docs: Small docs fixes
  docs/03-concepts/01-actor-lifecycle.mdx
  docs/03-concepts/04-actor-events.mdx
  docs/03-concepts/11-configuration.mdx
Labels: bug, t-platform, adhoc

#193 Improve unique key generation logic
  CHANGELOG.md
  pyproject.toml
  src/apify/_utils.py
  src/apify/scrapy/requests.py
  src/apify/scrapy/scheduler.py
  src/apify/storages/request_queue.py
  tests/unit/test_utils.py
Labels: t-tooling, tested

#195 docs: freeze dependencies of docs build
  pyproject.toml
Labels: adhoc, t-tooling
