Repository apify/apify-sdk-python, pull requests merged in 2024-10, with the labels that each got.

#284 fix: adjust tests of scrapy user data
  tests/unit/scrapy/requests/test_to_apify_request.py
Labels: adhoc, t-tooling, tested

#278 docs: Upgrade upgrading guide
  docs/03-concepts/03-storages.mdx
  docs/04-upgrading/upgrading_to_v2.md
Labels: adhoc, t-tooling

#286 chore: Add deprecation notice to actor standby port variable
  src/apify/_configuration.py
Labels: adhoc, t-tooling

#287 feat: add standby URL, change default standby port
  src/apify/_configuration.py
Labels: t-platform

#291 ci: update workflows and fix Python version reference
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/run_code_checks.yaml
  .github/workflows/run_release.yaml
  Makefile
Labels: adhoc, infrastructure, t-tooling

#292 ci: run code checks workflow only for PRs
  .github/workflows/run_code_checks.yaml
Labels: adhoc, infrastructure, t-tooling

#293 ci: fix PyPI project name, increase timeout for integration tests
  .github/workflows/_publish_to_pypi.yaml
  tests/integration/conftest.py
Labels: adhoc, infrastructure, t-tooling, tested

#295 ci: fix env reference in publish
  .github/workflows/_changelog_entry_check.yaml
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/_version_conflict_check.yaml
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/run_release.yaml
Labels: adhoc, t-tooling

#297 ci: align workflows with other repositories
  .github/workflows/_changelog_entry_check.yaml
  .github/workflows/_version_conflict_check.yaml
  .github/workflows/build_and_deploy_docs.yaml
  Makefile
Labels: adhoc, infrastructure, t-tooling

#294 chore: rm classes from tests and improve their names
  tests/integration/test_actor_api_helpers.py
  tests/integration/test_actor_create_proxy_configuration.py
  tests/integration/test_actor_dataset.py
  tests/integration/test_actor_events.py
  tests/integration/test_actor_key_value_store.py
  tests/integration/test_actor_lifecycle.py
  tests/integration/test_actor_log.py
  tests/integration/test_actor_request_queue.py
  tests/integration/test_fixtures.py
  tests/integration/test_request_queue.py
  tests/unit/actor/test_actor_create_proxy_configuration.py
  tests/unit/actor/test_actor_dataset.py
  tests/unit/actor/test_actor_env_helpers.py
  tests/unit/actor/test_actor_helpers.py
  tests/unit/actor/test_actor_key_value_store.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/actor/test_actor_log.py
  tests/unit/actor/test_actor_non_default_instance.py
  tests/unit/actor/test_actor_request_queue.py
  tests/unit/scrapy/middlewares/test_apify_proxy.py
  tests/unit/scrapy/pipelines/test_actor_dataset_push.py
  tests/unit/scrapy/requests/test_to_apify_request.py
  tests/unit/scrapy/requests/test_to_scrapy_request.py
  tests/unit/scrapy/utils/test_apply_apify_settings.py
  tests/unit/scrapy/utils/test_get_basic_auth_header.py
  tests/unit/test_crypto.py
  tests/unit/test_event_manager.py
  tests/unit/test_platform_event_manager.py
  tests/unit/test_proxy_configuration.py
Labels: adhoc, t-tooling, tested

#303 fix: Allow empty timeout_at env variable
  src/apify/_configuration.py
Labels: adhoc, t-tooling

#304 feat: add crawlee version to system info print
  src/apify/_utils.py
Labels: enhancement, adhoc, t-tooling

#306 chore: remove temporarily integration tests for releases
  .github/workflows/run_release.yaml
Labels: adhoc, infrastructure, t-tooling

#305 chore: bump version to 2.0.2
  CHANGELOG.md
  pyproject.toml
Labels: adhoc, t-tooling

#311 ci: Make integrations tests more stable
  .github/workflows/run_release.yaml
  src/apify/scrapy/middlewares/apify_proxy.py
  src/apify/scrapy/pipelines/actor_dataset_push.py
  src/apify/scrapy/scheduler.py
  tests/integration/README.md
  tests/integration/conftest.py
  tests/integration/test_actor_api_helpers.py
  tests/integration/test_actor_create_proxy_configuration.py
  tests/integration/test_actor_dataset.py
  tests/integration/test_actor_events.py
  tests/integration/test_actor_key_value_store.py
  tests/integration/test_actor_lifecycle.py
  tests/integration/test_actor_log.py
  tests/integration/test_actor_request_queue.py
  tests/integration/test_fixtures.py
  tests/integration/test_request_queue.py
  tests/unit/conftest.py
Labels: t-tooling, tested

#302 ci: Automate the release process
  .github/workflows/_changelog_entry_check.yaml
  .github/workflows/_version_conflict_check.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
  .github/workflows/run_release.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  scripts/check_changelog_entry.py
  scripts/check_version_conflict.py
  scripts/print_current_package_version.py
  scripts/update_version_for_prerelease.py
  scripts/utils.py
Labels: t-tooling

#312 chore: Upgrade to Crawlee 0.3.9
  .pre-commit-config.yaml
  pyproject.toml
Labels: t-tooling

#313 chore: update dev deps
  pyproject.toml
  tests/unit/test_platform_event_manager.py
Labels: adhoc, t-tooling, tested
