Repository apify/apify-sdk-python, pull requests merged in 2024-08, with the labels that each got.

#244 ci: Fix PyPI deploy
  .github/workflows/release.yaml
Labels: adhoc, t-tooling

#245 docs: Update a part of docs for 2.0
  docs/03-concepts/01-actor-lifecycle.mdx
  docs/03-concepts/04-actor-events.mdx
  docs/03-concepts/11-configuration.mdx
Labels: adhoc, t-tooling

#247 chore: migrate to Poetry and update tooling just like in Crawlee
  .github/workflows/check_pr_title.yaml
  .github/workflows/release.yaml
  .github/workflows/update_new_issue.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  pyproject.toml
  renovate.json
  scripts/check_version_in_changelog.py
  scripts/update_version_for_prerelease.py
  src/apify/_actor.py
  src/apify/_configuration.py
  src/apify/_crypto.py
  src/apify/_platform_event_manager.py
  src/apify/_proxy_configuration.py
  src/apify/apify_storage_client/_dataset_client.py
  src/apify/apify_storage_client/_key_value_store_client.py
  src/apify/apify_storage_client/_key_value_store_collection_client.py
  src/apify/scrapy/middlewares/apify_proxy.py
  src/apify/scrapy/requests.py
  src/apify/scrapy/scheduler.py
  src/apify/scrapy/utils.py
  tests/integration/conftest.py
  tests/integration/test_actor_api_helpers.py
  tests/integration/test_actor_create_proxy_configuration.py
  tests/integration/test_actor_events.py
  tests/integration/test_actor_log.py
  tests/unit/actor/test_actor_create_proxy_configuration.py
  tests/unit/actor/test_actor_env_helpers.py
  tests/unit/actor/test_actor_helpers.py
  tests/unit/actor/test_actor_key_value_store.py
  tests/unit/actor/test_actor_log.py
  tests/unit/conftest.py
  tests/unit/scrapy/middlewares/test_apify_proxy.py
  tests/unit/scrapy/pipelines/test_actor_dataset_push.py
  tests/unit/scrapy/requests/test_to_apify_request.py
  tests/unit/scrapy/requests/test_to_scrapy_request.py
  tests/unit/test_event_manager.py
  tests/unit/test_proxy_configuration.py
Labels: t-tooling, tested

#251 ci: fix update new issue trigger
  .github/workflows/update_new_issue.yaml
Labels: adhoc, t-tooling

#252 chore: add missing `py.typed` files to subpackages
  src/apify/apify_storage_client/py.typed
  src/apify/scrapy/middlewares/py.typed
  src/apify/scrapy/pipelines/py.typed
  src/apify/scrapy/py.typed
  src/apify/storages/py.typed
Labels: adhoc, t-tooling

#249 fix: Make apify.log public again
  src/apify/_actor.py
  src/apify/_platform_event_manager.py
  src/apify/_proxy_configuration.py
  src/apify/log.py
  tests/integration/actor_source_base/src/__main__.py
  tests/integration/test_actor_log.py
  tests/unit/actor/test_actor_log.py
Labels: adhoc, t-tooling, tested

#254 chore: Remove unnecessary deps
  pyproject.toml
  tests/unit/test_event_manager.py
Labels: adhoc, t-tooling, tested

#256 feat: Better Actor API typing
  docs/04-upgrading/upgrading_to_v20.md
  src/apify/__init__.py
  src/apify/_actor.py
  src/apify/_models.py
  tests/integration/test_actor_api_helpers.py
  tests/unit/actor/test_actor_helpers.py
Labels: t-tooling, tested
