Repository apify/apify-sdk-python, pull requests merged in 2024-12, with the labels that each got.

#347 fix: add upper bound of HTTPX version
  docs/02-guides/01-requests-and-httpx.mdx
  docs/03-concepts/05-proxy-management.mdx
  poetry.lock
  pyproject.toml
  src/apify/_proxy_configuration.py
  tests/unit/conftest.py
Labels: adhoc, t-tooling, tested

#353 chore: skip python 3.13 flaky test
  tests/unit/actor/test_actor_lifecycle.py
Labels: adhoc, t-tooling, tested

#351 feat: add new config variables to `Actor.config`
  poetry.lock
  pyproject.toml
  src/apify/_configuration.py
  tests/unit/actor/test_actor_env_helpers.py
Labels: t-platform, adhoc, tested

#356 fix: Better error message when attempting to use force_cloud without an Apify token
  src/apify/_actor.py
Labels: adhoc, t-tooling

#359 ci: Do not build a Docker image with prerelease SDK versions
  .github/workflows/pre_release.yaml
Labels: adhoc, t-tooling

#361 fix: allow calling `Actor.reboot()` from migrating handler, align reboot behavior with JS SDK
  docs/03-concepts/04-actor-events.mdx
  poetry.lock
  pyproject.toml
  src/apify/_actor.py
Labels: t-platform, adhoc

#363 chore: relax HTTPX version upper bound
  poetry.lock
  pyproject.toml
Labels: t-tooling
