Repository apify/apify-sdk-python, pull requests merged in 2024-01, with the labels that each got.

#158 Add Scrapy `ApifyHttpProxyMiddleware` for managing proxies
  src/apify/scrapy/__init__.py
  src/apify/scrapy/middlewares/__init__.py
  src/apify/scrapy/middlewares/apify_proxy.py
  src/apify/scrapy/middlewares/apify_retry.py
  src/apify/scrapy/utils.py
  tests/unit/scrapy/__init__.py
  tests/unit/scrapy/middlewares/__init__.py
  tests/unit/scrapy/middlewares/test_apify_proxy.py
  tests/unit/scrapy/test_utils.py
Labels: t-tooling, tested

#167 Add option to run integration tests from PRs from forks
  .github/workflows/check_version_availability.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/run_checks.yaml
  .github/workflows/unit_tests.yaml
  CHANGELOG.md
Labels: t-platform, adhoc

#168 Do not close `nested_event_loop` in the `Scheduler.__del__`
  CHANGELOG.md
  src/apify/scrapy/scheduler.py
Labels: t-tooling

#162 docs: add codeowner for documentation
  .github/CODEOWNERS
Labels: t-docs

#173 Add new subpackage for Scrapy pipelines
  src/apify/scrapy/__init__.py
  src/apify/scrapy/pipelines/__init__.py
  src/apify/scrapy/pipelines/actor_dataset_push.py
Labels: adhoc, t-tooling

#174 Replace asserts with custom checks in Scrapy subpackage
  CHANGELOG.md
  src/apify/scrapy/middlewares/apify_proxy.py
  src/apify/scrapy/middlewares/apify_retry.py
  src/apify/scrapy/scheduler.py
  src/apify/scrapy/utils.py
Labels: adhoc, t-tooling

#178 Add `apply_apify_settings` to Scrapy subpackage
  CHANGELOG.md
  src/apify/scrapy/utils.py
  tests/unit/scrapy/utils/test_apply_apify_settings.py
Labels: enhancement, adhoc, t-tooling

#179 Fixes conversion of `userData` and `headers` fields in Apify-Scrapy request translation
  CHANGELOG.md
  pyproject.toml
  src/apify/scrapy/__init__.py
  src/apify/scrapy/middlewares/apify_retry.py
  src/apify/scrapy/requests.py
  src/apify/scrapy/scheduler.py
  src/apify/scrapy/utils.py
  tests/unit/scrapy/requests/__init__.py
  tests/unit/scrapy/requests/test_to_apify_request.py
  tests/unit/scrapy/requests/test_to_scrapy_request.py
  tests/unit/scrapy/utils/test_to_apify_request.py
  tests/unit/scrapy/utils/test_to_scrapy_request.py
Labels: bug, adhoc, t-tooling
