Repository apify/apify-sdk-python, pull requests merged in 2024-11, with the labels that each got.

#315 fix: Fix CPU usage calculation
  src/apify/_platform_event_manager.py
  tests/unit/test_platform_event_manager.py
Labels: adhoc, t-tooling, tested

#319 test: Do not expect event handlers to be executed in any order
  src/apify/log.py
  tests/unit/test_platform_event_manager.py
Labels: adhoc, t-tooling, tested

#316 chore: update dev configs
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  website/.gitignore
Labels: adhoc, t-tooling

#322 fix: Set version constraint of the `websockets` dependency to <14.0.0
  pyproject.toml
Labels: bug, adhoc, t-tooling

#328 docs: reexport storages documentation from `crawlee-python`
  Makefile
  src/apify/_actor.py
  src/apify/_configuration.py
  src/apify/_models.py
  src/apify/_platform_event_manager.py
  src/apify/_proxy_configuration.py
  src/apify/_utils.py
  src/apify/apify_storage_client/_apify_storage_client.py
  website/build_api_reference.sh
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/pydoc-markdown.yml
  website/pydoc-markdown/__init__.py
  website/pydoc-markdown/generate_ast.py
  website/pydoc-markdown/google_docstring_processor.py
  website/transformDocs.js
Labels: documentation, adhoc, t-tooling

#326 feat: Handle request list user input
  pyproject.toml
  src/apify/_actor.py
  src/apify/_configuration.py
  src/apify/_models.py
  src/apify/_platform_event_manager.py
  src/apify/scrapy/middlewares/apify_proxy.py
  src/apify/scrapy/pipelines/actor_dataset_push.py
  src/apify/scrapy/scheduler.py
  src/apify/scrapy/utils.py
  src/apify/storages/__init__.py
  src/apify/storages/_request_list.py
  tests/unit/actor/test_request_list.py
Labels: t-tooling, tested

#329 ci: update Renove schedule
  renovate.json
Labels: adhoc, t-tooling

#330 chore: Add version upper boundary for Crawlee
  poetry.lock
  pyproject.toml
  src/apify/scrapy/requests.py
  tests/unit/scrapy/pipelines/test_actor_dataset_push.py
  tests/unit/scrapy/requests/test_to_apify_request.py
  tests/unit/scrapy/requests/test_to_scrapy_request.py
Labels: adhoc, t-tooling, tested

#342 chore: update to Ruff 0.8
  poetry.lock
  pyproject.toml
  src/apify/__init__.py
  src/apify/scrapy/__init__.py
  src/apify/storages/__init__.py
  tests/integration/conftest.py
Labels: adhoc, t-tooling, tested

#345 chore: Use specific rule codes when ignoring type issues
  pyproject.toml
  src/apify/_configuration.py
  tests/integration/test_actor_events.py
  tests/unit/actor/test_actor_create_proxy_configuration.py
  tests/unit/actor/test_actor_env_helpers.py
  tests/unit/scrapy/middlewares/test_apify_proxy.py
  tests/unit/test_proxy_configuration.py
Labels: adhoc, t-tooling, tested
