Repository apify/apify-sdk-python, pull requests merged in 2024-05, with the labels that each got.

#201 chore: integration tests only on oldest and newest Py versions
  .github/workflows/integration_tests.yaml
Labels: adhoc, t-tooling

#206 fix: Set a timeout for Actor cleanup
  CHANGELOG.md
  src/apify/actor.py
Labels: t-tooling

#208 chore: fix pytest deps (no module named pkg_resources)
  Makefile
  pyproject.toml
Labels: bug, adhoc, t-tooling
