Repository apify/apify-sdk-python, pull requests merged in 2024-09, with the labels that each got.

#257 fix: Dataset list response handling
  src/apify/apify_storage_client/_dataset_client.py
Labels: adhoc, t-tooling

#258 fix: Ignore deprecated platform events
  src/apify/_platform_event_manager.py
Labels: adhoc, t-tooling

#259 fix: possible infinity loop in Apify-Scrapy proxy middleware
  src/apify/scrapy/middlewares/apify_proxy.py
  tests/unit/scrapy/middlewares/test_apify_proxy.py
Labels: bug, adhoc, t-tooling, tested

#264 docs: fix `/reference` docs build
  Makefile
Labels: adhoc, t-tooling

#265 chore: Do not install poetry in install-dev make target
  .github/workflows/check_version_availability.yaml
  .github/workflows/docs.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/release.yaml
  .github/workflows/unit_tests.yaml
  Makefile
Labels: adhoc, t-tooling

#261 fix: Hotfix for batch_add_requests batch size limit
  src/apify/apify_storage_client/_request_queue_client.py
  tests/integration/test_request_queue.py
Labels: adhoc, t-tooling, tested

#266 feat: expose Request from Crawlee
  .gitignore
  Makefile
  src/apify/__init__.py
Labels: adhoc, t-tooling

#269 docs: improve examples in readme
  README.md
Labels: documentation, adhoc, t-tooling

#272 chore: update changelog
  CHANGELOG.md
Labels: adhoc, t-tooling

#274 docs: update upgrade guide to v2
  CHANGELOG.md
  docs/04-upgrading/upgrading_to_v2.md
Labels: adhoc, t-tooling

#277 chore: revert hotfix for batch add requests in client
  pyproject.toml
  src/apify/apify_storage_client/_request_queue_client.py
Labels: adhoc, t-tooling

#279 docs: Remove logging setup from Actor structure guide
  docs/01-overview/03-structure.mdx
Labels: adhoc, t-tooling

#282 docs: hotfix API reference docs
  src/apify/_crypto.py
  src/apify/_platform_event_manager.py
  src/apify/_proxy_configuration.py
  src/apify/log.py
  src/apify/scrapy/requests.py
  src/apify/scrapy/utils.py
  website/pydoc-markdown.yml
  website/transformDocs.js
Labels: t-tooling

#283 docs: add Google-style docstring parser
  website/build_api_reference.sh
  website/docusaurus.config.js
  website/pydoc-markdown/__init__.py
  website/pydoc-markdown/generate_ast.py
  website/pydoc-markdown/google_docstring_processor.py
  website/src/css/custom.css
  website/transformDocs.js
Labels: adhoc, t-tooling
