Repository apify/apify-sdk-python, pull requests merged in 2024-07, with the labels that each got.

#220 feat: add actor standby port
  CHANGELOG.md
  pyproject.toml
  src/apify/config.py
Labels: t-platform, adhoc

#222 chore: bump version to 1.7.3
  CHANGELOG.md
  pyproject.toml
Labels: adhoc, t-tooling

#221 chore: upgrade apify client to 1.7.1
  CHANGELOG.md
  pyproject.toml
Labels: adhoc, t-tooling

#224 chore: update dev deps & fix linter
  pyproject.toml
  src/apify/_memory_storage/resource_clients/base_resource_client.py
  src/apify/_utils.py
  src/apify/log.py
  src/apify/proxy_configuration.py
  tests/integration/test_actor_api_helpers.py
  tests/unit/actor/test_actor_log.py
  tests/unit/memory_storage/resource_clients/test_key_value_store.py
  tests/unit/test_utils.py
Labels: adhoc, t-tooling, tested

#225 ci: Stop testing python 3.8
  .github/workflows/check_version_availability.yaml
  .github/workflows/docs.yaml
  .github/workflows/integration_tests.yaml
  .github/workflows/lint_and_type_checks.yaml
  .github/workflows/unit_tests.yaml
Labels: adhoc, t-tooling
