Repository apify/apify-sdk-python, pull requests merged in 2025-01, with the labels that each got.

#355 feat: Upgrade to Crawlee v0.5
  poetry.lock
  pyproject.toml
  src/apify/_actor.py
  src/apify/_configuration.py
  src/apify/_proxy_configuration.py
  src/apify/apify_storage_client/_apify_storage_client.py
  src/apify/apify_storage_client/_dataset_client.py
  src/apify/apify_storage_client/_dataset_collection_client.py
  src/apify/apify_storage_client/_key_value_store_client.py
  src/apify/apify_storage_client/_key_value_store_collection_client.py
  src/apify/apify_storage_client/_request_queue_client.py
  src/apify/apify_storage_client/_request_queue_collection_client.py
  src/apify/log.py
  src/apify/storages/_request_list.py
  tests/integration/conftest.py
  tests/unit/actor/test_actor_dataset.py
  tests/unit/actor/test_actor_key_value_store.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/actor/test_actor_non_default_instance.py
  tests/unit/actor/test_request_list.py
  tests/unit/conftest.py
  tests/unit/test_proxy_configuration.py
Labels: enhancement, adhoc, t-tooling, tested

#371 ci: Add workflow dispatch for pre-release workflow
  .github/workflows/pre_release.yaml
Labels: adhoc, infrastructure, t-tooling

#354 fix: Better event listener type definitions
  poetry.lock
  src/apify/__init__.py
  src/apify/_actor.py
Labels: t-tooling

#380 docs: fix links and some headings
  docs/01_overview/01_introduction.mdx
  docs/01_overview/02_running_actors_locally.mdx
  docs/01_overview/03_actor_structure.mdx
  docs/02_guides/01_beautifulsoup_httpx.mdx
  docs/02_guides/02_crawlee.mdx
  docs/02_guides/03_playwright.mdx
  docs/02_guides/04_selenium.mdx
  docs/02_guides/05_scrapy.mdx
  docs/03_concepts/01_actor_lifecycle.mdx
  docs/03_concepts/02_actor_input.mdx
  docs/03_concepts/03_storages.mdx
  docs/03_concepts/04_actor_events.mdx
  docs/03_concepts/06_interacting_with_other_actors.mdx
  docs/03_concepts/07_webhooks.mdx
  docs/03_concepts/08_access_apify_api.mdx
  docs/03_concepts/09_running_webserver.mdx
  docs/03_concepts/10_logging.mdx
  docs/03_concepts/11_configuration.mdx
Labels: documentation, adhoc, t-tooling

#385 fix: Fix RQ usage in Scrapy scheduler
  src/apify/_actor.py
  src/apify/scrapy/middlewares/apify_proxy.py
  src/apify/scrapy/scheduler.py
Labels: t-tooling
