Repository apify/apify-sdk-python, pull requests merged in 2025-02, with the labels that each got.

#381 docs: bump `docusaurus-plugin-typedoc-api`
  website/package-lock.json
  website/package.json
Labels: adhoc, t-tooling

#394 chore(ci): unblock stalling documentation build
  .github/workflows/build_and_deploy_docs.yaml
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
  website/src/pages/index.module.css
Labels: adhoc, t-tooling

#390 feat: Unify Apify and Scrapy to use single event loop & remove `nest-asyncio`
  docs/02_guides/05_scrapy.mdx
  docs/02_guides/code/scrapy_project/src/__init__.py
  docs/02_guides/code/scrapy_project/src/__main__.py
  docs/02_guides/code/scrapy_project/src/items.py
  docs/02_guides/code/scrapy_project/src/main.py
  docs/02_guides/code/scrapy_project/src/py.typed
  docs/02_guides/code/scrapy_project/src/settings.py
  docs/02_guides/code/scrapy_project/src/spiders/__init__.py
  docs/02_guides/code/scrapy_project/src/spiders/py.typed
  docs/02_guides/code/scrapy_project/src/spiders/title.py
  docs/02_guides/code/scrapy_src/__main__.py
  docs/02_guides/code/scrapy_src/items.py
  docs/02_guides/code/scrapy_src/main.py
  docs/02_guides/code/scrapy_src/settings.py
  docs/02_guides/code/scrapy_src/spiders/py.typed
  pyproject.toml
  src/apify/_actor.py
  src/apify/scrapy/__init__.py
  src/apify/scrapy/_actor_runner.py
  src/apify/scrapy/_async_thread.py
  src/apify/scrapy/_logging_config.py
  src/apify/scrapy/middlewares/apify_proxy.py
  src/apify/scrapy/pipelines/actor_dataset_push.py
  src/apify/scrapy/requests.py
  src/apify/scrapy/scheduler.py
  src/apify/scrapy/utils.py
  tests/integration/README.md
  tests/integration/conftest.py
  tests/integration/test_actor_scrapy.py
  tests/unit/scrapy/utils/test_apply_apify_settings.py
Labels: t-tooling, tested

#402 fix: Make sure that Actor instances with non-default configurations are also accessible through the global Actor proxy after initialization
  src/apify/_actor.py
  tests/unit/actor/test_actor_non_default_instance.py
  tests/unit/conftest.py
Labels: t-tooling, tested

#398 docs: Set line length to docs related code to 90
  docs/01_overview/code/01_introduction.py
  docs/02_guides/code/02_crawlee_beautifulsoup.py
  docs/02_guides/code/02_crawlee_playwright.py
  docs/02_guides/code/scrapy_project/src/__main__.py
  docs/02_guides/code/scrapy_project/src/spiders/title.py
  docs/03_concepts/code/03_rq.py
  docs/03_concepts/code/05_proxy_actor_input.py
  docs/03_concepts/code/05_proxy_rotation.py
  docs/03_concepts/code/09_webserver.py
  docs/pyproject.toml
Labels: documentation, adhoc, t-tooling

#393 feat: Support pay-per-event via `Actor.charge`
  poetry.lock
  pyproject.toml
  src/apify/_actor.py
  src/apify/_charging.py
  src/apify/_configuration.py
  src/apify/_models.py
  src/apify/_utils.py
  tests/integration/conftest.py
  tests/integration/test_actor_charge.py
  tests/unit/actor/test_actor_env_helpers.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/actor/test_actor_log.py
Labels: t-tooling, tested

#406 chore: migrate to uv package manager
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
  .gitignore
  CONTRIBUTING.md
  Makefile
  poetry.lock
  pyproject.toml
  uv.lock
Labels: t-tooling

#409 ci: switch apify workflow branch back to main
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
Labels: t-tooling

#410 docs: update code example for Scrapy guide
  docs/02_guides/code/scrapy_project/src/__main__.py
  docs/02_guides/code/scrapy_project/src/settings.py
  docs/02_guides/code/scrapy_project/src/spiders/__init__.py
  docs/02_guides/code/scrapy_project/src/spiders/title.py
Labels: documentation, adhoc, t-tooling

#413 fix: Allow None value in 'inputBodyLen' in ActorRunStats
  src/apify/_models.py
Labels: adhoc, t-tooling

#417 docs: bump `typedoc-api` plugin
  website/package-lock.json
  website/package.json
Labels: adhoc, t-tooling

#415 docs: Add force_cloud argument documentation
  docs/03_concepts/03_storages.mdx
Labels: documentation, t-tooling
