Repository apify/apify-sdk-python, pull requests merged in 2025-03, with the labels that each got.

#420 feat: update to Crawlee v0.6
  pyproject.toml
  src/apify/_actor.py
  src/apify/apify_storage_client/_apify_storage_client.py
  src/apify/apify_storage_client/_dataset_client.py
  src/apify/apify_storage_client/_dataset_collection_client.py
  src/apify/apify_storage_client/_key_value_store_client.py
  src/apify/apify_storage_client/_key_value_store_collection_client.py
  src/apify/apify_storage_client/_request_queue_client.py
  src/apify/apify_storage_client/_request_queue_collection_client.py
  src/apify/storages/_request_list.py
  tests/integration/test_actor_log.py
  uv.lock
Labels: adhoc, t-tooling, tested

#424 feat: add Actor `exit_process` option
  src/apify/_actor.py
  tests/unit/actor/test_actor_log.py
Labels: t-tooling, tested

#416 docs: Add PPE guide
  docs/03_concepts/12_pay_per_event.mdx
  docs/03_concepts/code/actor_charge.py
  docs/03_concepts/code/conditional_actor_charge.py
  website/src/components/ApiLink.jsx
  website/src/components/Gradients.jsx
  website/src/components/Highlights.jsx
  website/src/components/Highlights.module.css
  website/src/components/RunnableCodeBlock.jsx
  website/src/components/RunnableCodeBlock.module.css
Labels: adhoc, t-tooling

#425 feat: upgrade websockets to v14 to adapt to library API changes
  pyproject.toml
  src/apify/_platform_event_manager.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/test_platform_event_manager.py
  uv.lock
Labels: t-tooling

#431 chore: update Ruff to v0.10
  pyproject.toml
  src/apify/_actor.py
  src/apify/scrapy/requests.py
  tests/unit/actor/test_actor_lifecycle.py
  uv.lock
Labels: adhoc, t-tooling, tested

#433 chore(deps): rm unused dev deps
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#435 chore(deps): add build dev dep
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#403 feat: Implement Scrapy HTTP cache backend
  .github/workflows/run_code_checks.yaml
  docs/02_guides/05_scrapy.mdx
  docs/02_guides/code/scrapy_project/src/settings.py
  src/apify/scrapy/extensions/__init__.py
  src/apify/scrapy/extensions/_httpcache.py
  src/apify/scrapy/utils.py
  tests/unit/scrapy/extensions/__init__.py
  tests/unit/scrapy/extensions/test_httpcache.py
Labels: enhancement, t-tooling

#440 docs: fix changelog generation by bumping `@apify/docs-theme` plugin
  website/package-lock.json
  website/package.json
Labels: adhoc, t-tooling

#448 chore: fix Scrapy flaky integration test
  tests/integration/test_actor_scrapy.py
Labels: adhoc, t-tooling, tested

#447 fix: Fix calculation of CPU utilization from SystemInfo events
  src/apify/_platform_event_manager.py
Labels: adhoc, t-tooling

#441 chore: Disable browser sandbox when running on Apify platform
  src/apify/_configuration.py
  tests/unit/actor/test_configuration.py
Labels: adhoc, t-tooling, tested
