Repository apify/apify-sdk-python, pull requests merged in 2025-08, with the labels that each got.

#530 chore: Skip concurrent processing RQ test
  tests/integration/test_request_queue.py
Labels: adhoc, t-tooling, tested

#535 chore: Add test ignored env var `USER_IS_PAYING`
  tests/unit/actor/test_actor_env_helpers.py
  uv.lock
Labels: adhoc, t-tooling, tested

#544 fix: Try to solve race conditions
  src/apify/storage_clients/_apify/_request_queue_client.py
  tests/integration/test_actor_request_queue.py
  tests/integration/test_crawlers_with_storages.py
Labels: t-tooling

#534 feat: Add deduplication to `add_batch_of_requests`
  src/apify/storage_clients/_apify/_request_queue_client.py
  tests/integration/test_actor_request_queue.py
  uv.lock
Labels: enhancement, t-tooling, tested

#555 fix: Resolve DeprecationWarning in ApifyEventManager
  src/apify/_actor.py
  src/apify/events/_apify_event_manager.py
Labels: t-tooling

#559 chore: Polish dev deps
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#553 refactor!: Remove `Request.id` field
  docs/03_concepts/code/03_rq.py
  docs/04_upgrading/upgrading_to_v3.md
  src/apify/scrapy/requests.py
  src/apify/storage_clients/_apify/_models.py
  src/apify/storage_clients/_apify/_request_queue_client.py
  tests/integration/test_actor_request_queue.py
  tests/integration/test_request_queue.py
  tests/unit/scrapy/requests/test_to_apify_request.py
  tests/unit/scrapy/requests/test_to_scrapy_request.py
  tests/unit/storage_clients/test_apify_request_queue_client.py
  uv.lock
Labels: t-tooling, tested

#561 chore: Update to Crawlee v1.0.0rc1
  pyproject.toml
  tests/integration/actor_source_base/requirements.txt
  uv.lock
Labels: adhoc, t-tooling

#563 ci: Fix release pipeline
  .github/workflows/release.yaml
Labels: adhoc, t-tooling

#564 chore: Cleanup after 3.0.0rc1 release
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#552 fix: Use same `client_key` for `Actor` created `request_queue` and improve its metadata estimation
  src/apify/storage_clients/_apify/_request_queue_client.py
  tests/integration/_utils.py
  tests/integration/conftest.py
  tests/integration/test_actor_request_queue.py
  tests/integration/test_request_queue.py
  uv.lock
  website/package-lock.json
  website/package.json
Labels: t-tooling, tested
