Repository apify/apify-sdk-python, pull requests merged in 2025-07, with the labels that each got.

#490 chore: resolve Pytest warnings
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#491 chore: update project metadata
  pyproject.toml
Labels: adhoc, t-tooling

#494 ci: fix Apify workflows integration tests reference
  .github/workflows/run_code_checks.yaml
Labels: adhoc, t-tooling

#495 ci: Update Python versions in code checks
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
Labels: adhoc, t-tooling

#496 ci: Update Python versions in release pipelines
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
Labels: adhoc, t-tooling

#493 chore: Bump minimum Python version to 3.10
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
  CONTRIBUTING.md
  docs/01_overview/02_running_actors_locally.mdx
  pyproject.toml
  src/apify/_actor.py
  src/apify/_charging.py
  src/apify/_models.py
  src/apify/_platform_event_manager.py
  src/apify/_utils.py
  src/apify/storages/_request_list.py
  tests/integration/conftest.py
  tests/integration/test_actor_events.py
  tests/unit/actor/test_actor_lifecycle.py
  tests/unit/conftest.py
  tests/unit/test_platform_event_manager.py
  uv.lock
Labels: t-tooling, tested

#482 feat(crypto): decrypt secret objects
  src/apify/_consts.py
  src/apify/_crypto.py
  tests/unit/actor/test_actor_key_value_store.py
Labels: t-console, tested

#498 chore: resolve linter issues
  src/apify/_consts.py
  src/apify/_crypto.py
  tests/unit/actor/test_actor_key_value_store.py
Labels: adhoc, t-tooling, tested

#500 fix: sync `@docusaurus` theme version [internal]
  website/package-lock.json
  website/package.json
Labels: bug, adhoc, t-web

#501 fix: tagline overlap
  website/src/pages/index.module.css
Labels: bug, adhoc, t-web

#509 docs: Improve API doc groups
  src/apify/_actor.py
  src/apify/_charging.py
  src/apify/_configuration.py
  src/apify/_crypto.py
  src/apify/_models.py
  src/apify/_platform_event_manager.py
  src/apify/_proxy_configuration.py
  src/apify/_utils.py
  src/apify/apify_storage_client/_apify_storage_client.py
  src/apify/log.py
  src/apify/storages/_request_list.py
  website/docusaurus.config.js
Labels: t-tooling

#521 ci: Fix changelog generation
  .github/workflows/pre_release.yaml
  CHANGELOG.md
  pyproject.toml
Labels: adhoc, t-tooling

#523 fix: Restrict apify-shared and apify-client versions
  pyproject.toml
  uv.lock
Labels: adhoc, t-tooling

#526 docs: respect scripts and customFields from shared config
  website/docusaurus.config.js
Labels: adhoc, t-tooling
